syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.example.reservationprice";
option java_outer_classname = "ReservationPriceProto";

service ReservationPriceService {
  rpc CalculatePrice (PriceRequest) returns (PriceResponse) {}
  rpc UpdatePrice (UpdatePriceRequest) returns (PriceResponse) {}
}

message PriceRequest {
  int64 reservation_id = 1;
  int32 number_of_guests = 2;
  string table_type = 3;
  int32 duration_hours = 4;
}

message PriceResponse {
  int64 reservation_id = 1;
  double price = 2;
  string verdict = 3;
}

message UpdatePriceRequest {
  int64 reservation_id = 1;
  int32 new_number_of_guests = 2;
}